version: '3'
services:
  rabbitmq-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest